version: '3.4'

services:
  calculator:
    image: calculator
    build:
      context: .
      dockerfile: ./Dockerfile_git_task
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
